import { int, float, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  // Crypto Board access control
  cryptoBoardAccess: int("cryptoBoardAccess").default(0).notNull(), // 0=no access, 1=has access
  accessExpiresAt: timestamp("accessExpiresAt"),  // null = no expiry (if access=1, permanent)
  accessGrantedAt: timestamp("accessGrantedAt"),  // when access was granted
  accessNote: text("accessNote"),                  // admin note about this grant
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Announcements table — admin-managed bulletins displayed on dashboard
 */
export const announcements = mysqlTable("announcements", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  content: text("content").notNull(),
  imageUrl: text("imageUrl"),
  imageCaption: varchar("imageCaption", { length: 512 }),
  isActive: int("isActive").default(1).notNull(),
  authorId: int("authorId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Announcement = typeof announcements.$inferSelect;
export type InsertAnnouncement = typeof announcements.$inferInsert;

/**
 * Stock recommendations — auto-generated by strategy engine
 * Stores Top 10 picks per market with scoring details
 */
export const stockRecommendations = mysqlTable("stock_recommendations", {
  id: int("id").autoincrement().primaryKey(),
  market: varchar("market", { length: 20 }).notNull(),  // cn, hk, us, crypto
  rank: int("rank").notNull(),
  code: varchar("code", { length: 20 }).notNull(),
  symbol: varchar("symbol", { length: 30 }).notNull(),
  nameZh: varchar("nameZh", { length: 100 }).notNull(),
  nameEn: varchar("nameEn", { length: 100 }).notNull(),
  industry: varchar("industry", { length: 50 }),
  price: float("price").default(0).notNull(),
  change: float("priceChange").default(0).notNull(),
  changePercent: float("changePercent").default(0).notNull(),
  score: float("score").default(0).notNull(),
  signal: varchar("signal", { length: 20 }).default("hold").notNull(),
  pe: float("pe"),
  pb: float("pb"),
  dividendYield: float("dividendYield"),
  capitalFlow: float("capitalFlow").default(0),
  reason: text("reason"),
  reasonDetail: text("reasonDetail"),
  tags: varchar("tags", { length: 500 }),
  batchId: varchar("batchId", { length: 36 }).notNull(),  // group by update batch
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StockRecommendation = typeof stockRecommendations.$inferSelect;

/**
 * Market sentiment — auto-generated by strategy engine
 */
export const marketSentiment = mysqlTable("market_sentiment_data", {
  id: int("id").autoincrement().primaryKey(),
  market: varchar("market", { length: 20 }).notNull(),
  advanceRatio: float("advanceRatio").default(50),
  mainForceFlow: float("mainForceFlow").default(0),
  marketState: varchar("marketState", { length: 20 }).default("neutral"),
  stopLoss: float("stopLoss"),
  positionSuggestion: float("positionSuggestion"),
  advice: text("advice"),
  batchId: varchar("batchId", { length: 36 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type MarketSentimentData = typeof marketSentiment.$inferSelect;

/**
 * Simulated portfolio — tracks virtual positions for crypto board
 * One active portfolio at a time, $10,000 initial capital
 */
export const simPortfolio = mysqlTable("sim_portfolio", {
  id: int("id").autoincrement().primaryKey(),
  symbol: varchar("symbol", { length: 20 }).notNull(),       // e.g. BTC, ETH, TRUMP
  name: varchar("name", { length: 100 }).notNull(),
  category: varchar("category", { length: 20 }).notNull(),   // mainstream / meme
  entryPrice: float("entryPrice").notNull(),                  // avg entry price USD
  currentPrice: float("currentPrice").notNull(),              // latest price USD
  quantity: float("quantity").notNull(),                      // amount of coins
  costBasis: float("costBasis").notNull(),                    // total cost USD
  currentValue: float("currentValue").notNull(),              // current value USD
  pnl: float("pnl").default(0).notNull(),                    // unrealized P&L USD
  pnlPercent: float("pnlPercent").default(0).notNull(),       // unrealized P&L %
  weight: float("weight").default(0).notNull(),               // portfolio weight %
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SimPortfolio = typeof simPortfolio.$inferSelect;

/**
 * Simulated trades — buy/sell history log
 */
export const simTrades = mysqlTable("sim_trades", {
  id: int("id").autoincrement().primaryKey(),
  symbol: varchar("symbol", { length: 20 }).notNull(),
  name: varchar("name", { length: 100 }).notNull(),
  action: varchar("action", { length: 10 }).notNull(),       // BUY / SELL
  price: float("price").notNull(),                            // execution price
  quantity: float("quantity").notNull(),                      // amount
  value: float("value").notNull(),                            // total value USD
  reason: varchar("reason", { length: 500 }),                 // why this trade
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimTrade = typeof simTrades.$inferSelect;

/**
 * Simulated daily snapshots — track portfolio value over time
 */
export const simSnapshots = mysqlTable("sim_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  totalValue: float("totalValue").notNull(),                  // total portfolio value
  cashBalance: float("cashBalance").notNull(),                // remaining cash
  investedValue: float("investedValue").notNull(),            // value in positions
  totalPnl: float("totalPnl").default(0).notNull(),           // total P&L USD
  totalPnlPercent: float("totalPnlPercent").default(0).notNull(), // total P&L %
  positionCount: int("positionCount").default(0).notNull(),
  snapshotTime: varchar("snapshotTime", { length: 10 }).notNull(), // "06:00" or "22:00"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimSnapshot = typeof simSnapshots.$inferSelect;

/**
 * Simulated portfolio config — tracks start date and initial capital
 */
export const simConfig = mysqlTable("sim_config", {
  id: int("id").autoincrement().primaryKey(),
  initialCapital: float("initialCapital").default(10000).notNull(),
  startDate: timestamp("startDate").defaultNow().notNull(),
  isActive: int("isActive").default(1).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimConfig = typeof simConfig.$inferSelect;

/**
 * Crypto Board cache — persists latest successful data fetch
 * Survives server restarts and API rate limiting
 */
export const cryptoBoardCache = mysqlTable("crypto_board_cache", {
  id: int("id").autoincrement().primaryKey(),
  dataKey: varchar("dataKey", { length: 50 }).notNull().unique(), // 'latest'
  jsonData: text("jsonData").notNull(),                            // full JSON blob
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CryptoBoardCacheRow = typeof cryptoBoardCache.$inferSelect;

/**
 * Visitor logs — tracks every page visit with IP geolocation
 * Used by admin analytics dashboard
 */
export const visitorLogs = mysqlTable("visitor_logs", {
  id: int("id").autoincrement().primaryKey(),
  ip: varchar("ip", { length: 45 }).notNull(),           // IPv4 or IPv6
  path: varchar("path", { length: 512 }).notNull(),       // visited URL path
  method: varchar("method", { length: 10 }).default("GET").notNull(),
  userAgent: text("userAgent"),
  referer: varchar("referer", { length: 1024 }),
  // Geolocation from IP-API
  country: varchar("country", { length: 100 }),
  countryCode: varchar("countryCode", { length: 10 }),
  region: varchar("region", { length: 100 }),
  city: varchar("city", { length: 100 }),
  lat: float("lat"),
  lon: float("lon"),
  isp: varchar("isp", { length: 200 }),
  // Device info parsed from UA
  deviceType: varchar("deviceType", { length: 20 }),      // desktop / mobile / tablet / bot
  browser: varchar("browser", { length: 50 }),
  os: varchar("os", { length: 50 }),
  // User association (nullable for anonymous visitors)
  userId: int("userId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type VisitorLog = typeof visitorLogs.$inferSelect;
export type InsertVisitorLog = typeof visitorLogs.$inferInsert;

/**
 * Page access rules — admin-managed access control per page per user type
 * Controls which pages are visible to guests (unauthenticated) and registered users
 * Admin pages are always restricted to admin role only
 */
export const pageAccessRules = mysqlTable("page_access_rules", {
  id: int("id").autoincrement().primaryKey(),
  pagePath: varchar("pagePath", { length: 100 }).notNull().unique(), // e.g. '/', '/about', '/crypto-investment'
  pageLabel: varchar("pageLabel", { length: 100 }).notNull(),         // display name e.g. '首页', '关于'
  guestAccess: int("guestAccess").default(1).notNull(),               // 0=blocked, 1=allowed
  userAccess: int("userAccess").default(1).notNull(),                 // 0=blocked, 1=allowed (registered users)
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PageAccessRule = typeof pageAccessRules.$inferSelect;
export type InsertPageAccessRule = typeof pageAccessRules.$inferInsert;

/**
 * Site settings — global configuration flags
 * Used for features like "open all pages to everyone"
 */
export const siteSettings = mysqlTable("site_settings", {
  id: int("id").autoincrement().primaryKey(),
  settingKey: varchar("settingKey", { length: 100 }).notNull().unique(),
  settingValue: text("settingValue").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SiteSetting = typeof siteSettings.$inferSelect;

/**
 * A-Share Simulated Portfolio Config — ¥1,000,000 initial capital
 * Mirrors crypto sim_config but for A-share market
 */
export const simAshareConfig = mysqlTable("sim_ashare_config", {
  id: int("id").autoincrement().primaryKey(),
  initialCapital: float("initialCapital").default(1000000).notNull(), // ¥1,000,000 CNY
  startDate: timestamp("startDate").defaultNow().notNull(),
  isActive: int("isActive").default(1).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimAshareConfig = typeof simAshareConfig.$inferSelect;

/**
 * A-Share Simulated Portfolio — tracks virtual stock positions
 */
export const simAsharePortfolio = mysqlTable("sim_ashare_portfolio", {
  id: int("id").autoincrement().primaryKey(),
  symbol: varchar("symbol", { length: 20 }).notNull(),       // e.g. 600036.SS
  name: varchar("name", { length: 100 }).notNull(),
  category: varchar("category", { length: 20 }).notNull(),   // blueChip / growth / value
  industry: varchar("industry", { length: 50 }),
  entryPrice: float("entryPrice").notNull(),                  // avg entry price CNY
  currentPrice: float("currentPrice").notNull(),              // latest price CNY
  quantity: int("quantity").notNull(),                         // number of shares (lots of 100)
  costBasis: float("costBasis").notNull(),                    // total cost CNY
  currentValue: float("currentValue").notNull(),              // current value CNY
  pnl: float("pnl").default(0).notNull(),                    // unrealized P&L CNY
  pnlPercent: float("pnlPercent").default(0).notNull(),       // unrealized P&L %
  weight: float("weight").default(0).notNull(),               // portfolio weight %
  score: float("score").default(0),                           // strategy score at buy time
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SimAsharePortfolio = typeof simAsharePortfolio.$inferSelect;

/**
 * A-Share Simulated Trades — buy/sell history log
 */
export const simAshareTrades = mysqlTable("sim_ashare_trades", {
  id: int("id").autoincrement().primaryKey(),
  symbol: varchar("symbol", { length: 20 }).notNull(),
  name: varchar("name", { length: 100 }).notNull(),
  action: varchar("action", { length: 10 }).notNull(),       // BUY / SELL
  price: float("price").notNull(),                            // execution price CNY
  quantity: int("quantity").notNull(),                         // number of shares
  value: float("value").notNull(),                            // total value CNY
  reason: varchar("reason", { length: 500 }),                 // why this trade
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimAshareTrade = typeof simAshareTrades.$inferSelect;

/**
 * A-Share Simulated Snapshots — track portfolio value over time
 */
export const simAshareSnapshots = mysqlTable("sim_ashare_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  totalValue: float("totalValue").notNull(),                  // total portfolio value CNY
  cashBalance: float("cashBalance").notNull(),                // remaining cash CNY
  investedValue: float("investedValue").notNull(),            // value in positions CNY
  totalPnl: float("totalPnl").default(0).notNull(),           // total P&L CNY
  totalPnlPercent: float("totalPnlPercent").default(0).notNull(), // total P&L %
  positionCount: int("positionCount").default(0).notNull(),
  strategy: varchar("strategy", { length: 50 }),              // current strategy mode
  snapshotTime: varchar("snapshotTime", { length: 10 }).notNull(), // "09:00"
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SimAshareSnapshot = typeof simAshareSnapshots.$inferSelect;

// Weekly P&L tracking for A-share simulation
// Each week: Mon 9:00 (start) → Fri 15:00 (end)
export const simAshareWeekly = mysqlTable("sim_ashare_weekly", {
  id: int("id").autoincrement().primaryKey(),
  weekLabel: varchar("weekLabel", { length: 20 }).notNull(),     // e.g. "2026-W13"
  weekStartDate: varchar("weekStartDate", { length: 10 }).notNull(), // e.g. "2026-03-23"
  weekEndDate: varchar("weekEndDate", { length: 10 }).notNull(),     // e.g. "2026-03-27"
  startValue: float("startValue").notNull(),                     // portfolio value at Mon 9:00
  endValue: float("endValue"),                                   // portfolio value at Fri 15:00 (null if week not ended)
  weeklyPnl: float("weeklyPnl"),                                 // end - start (null if week not ended)
  weeklyPnlPercent: float("weeklyPnlPercent"),                   // (end-start)/start*100
  startCash: float("startCash").notNull(),
  endCash: float("endCash"),
  startPositionCount: int("startPositionCount").default(0).notNull(),
  endPositionCount: int("endPositionCount"),
  strategy: varchar("strategy", { length: 50 }),
  isComplete: int("isComplete").default(0).notNull(),            // 0=in progress, 1=complete
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SimAshareWeekly = typeof simAshareWeekly.$inferSelect;
