import { int, float, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Announcements table — admin-managed bulletins displayed on dashboard
 */
export const announcements = mysqlTable("announcements", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  content: text("content").notNull(),
  imageUrl: text("imageUrl"),
  imageCaption: varchar("imageCaption", { length: 512 }),
  isActive: int("isActive").default(1).notNull(),
  authorId: int("authorId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Announcement = typeof announcements.$inferSelect;
export type InsertAnnouncement = typeof announcements.$inferInsert;

/**
 * Stock recommendations — auto-generated by strategy engine
 * Stores Top 10 picks per market with scoring details
 */
export const stockRecommendations = mysqlTable("stock_recommendations", {
  id: int("id").autoincrement().primaryKey(),
  market: varchar("market", { length: 20 }).notNull(),  // cn, hk, us, crypto
  rank: int("rank").notNull(),
  code: varchar("code", { length: 20 }).notNull(),
  symbol: varchar("symbol", { length: 30 }).notNull(),
  nameZh: varchar("nameZh", { length: 100 }).notNull(),
  nameEn: varchar("nameEn", { length: 100 }).notNull(),
  industry: varchar("industry", { length: 50 }),
  price: float("price").default(0).notNull(),
  change: float("priceChange").default(0).notNull(),
  changePercent: float("changePercent").default(0).notNull(),
  score: float("score").default(0).notNull(),
  signal: varchar("signal", { length: 20 }).default("hold").notNull(),
  pe: float("pe"),
  pb: float("pb"),
  dividendYield: float("dividendYield"),
  capitalFlow: float("capitalFlow").default(0),
  reason: text("reason"),
  reasonDetail: text("reasonDetail"),
  tags: varchar("tags", { length: 500 }),
  batchId: varchar("batchId", { length: 36 }).notNull(),  // group by update batch
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StockRecommendation = typeof stockRecommendations.$inferSelect;

/**
 * Market sentiment — auto-generated by strategy engine
 */
export const marketSentiment = mysqlTable("market_sentiment_data", {
  id: int("id").autoincrement().primaryKey(),
  market: varchar("market", { length: 20 }).notNull(),
  advanceRatio: float("advanceRatio").default(50),
  mainForceFlow: float("mainForceFlow").default(0),
  marketState: varchar("marketState", { length: 20 }).default("neutral"),
  stopLoss: float("stopLoss"),
  positionSuggestion: float("positionSuggestion"),
  advice: text("advice"),
  batchId: varchar("batchId", { length: 36 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type MarketSentimentData = typeof marketSentiment.$inferSelect;
